export DOCKER_REPOSITORY='eyuel1'
export DOCKER_NAME='nlp_quora'
export DOCKER_TAG='1.0.0'


docker build -t ${DOCKER_REPOSITORY}/${DOCKER_NAME}:${DOCKER_TAG} .
docker tag ${DOCKER_REPOSITORY}/${DOCKER_NAME}:${DOCKER_TAG} ${DOCKER_REPOSITORY}/${DOCKER_NAME}:latest

docker run -it -p 8888:8888 ${DOCKER_REPOSITORY}/${DOCKER_NAME}:${DOCKER_TAG}